import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
function foodPage({ data }) {

    return(
        <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className='flex flex-col justify-center items-center min-h-screen'>
            <h1>{data.title}</h1>
          
  
  
  
  
  
        </main>
  
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    )


}

// This gets called on every request
export async function getServerSideProps(context) {

    const { id } = context.query
    const url = `https://api.spoonacular.com/recipes/${id}/information?&apiKey=${process.env.FOOD_API_KEY}`
    console.log("url for food/id page: ", url)
    // Fetch data from external API
    const result = await fetch(`${url}`, {
        method: "GET", 
        headers: {
          'Content-Type': 'application/json'
          // 'Content-Type': 'application/x-www-form-urlencoded',
        },
      })
      const data = await result.json()
      console.log("Server side fetch: ", data)

    // Pass data to the page via props
    return { props: { data } }
}

export default foodPage