import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
function foodPage({ data }) {
  if (!data) {
    return (
      <h1>No data found</h1>
    )
  }
  return (
    <div>
      <Head>
        <title>{data.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex flex-col items-center  min-h-screen w-4/5 m-auto'>
        <h1 className='mt-10 text-2xl text-center'>{data.title}</h1>
        <img className="rounded-md" src={data.image}></img>
        {/* Dangerously setting inner html is the only way to let the markup work, as far as I know*/}
        <div dangerouslySetInnerHTML={{__html:data["summary"]}}></div>
        <div className='flex flex-col lg:flex-row'>
          <div className=' bg-slate-400 text-white rounded-lg p-2 m-2'>
            <h2 className='text-center'>Ingredients:</h2>
            <ul>
              {
                data.extendedIngredients.map(ingredient => {
                  return <li key={ingredient.id + ingredient.amount}>
                    {ingredient.amount} {ingredient.unit} {ingredient.name}
                  </li>

                })


              }
            </ul>
          </div>
          <div className=' bg-slate-400 text-white rounded-lg p-2 m-2'>
            <h2 className='text-center'>Suitable Diets:</h2>
            <ul>
              {
                data.diets.map((diet, index) => {
                  return <li key={index}>{diet} </li>

                })


              }

            </ul>




          </div>





        </div>
        <p>{data.instructions}</p>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )


}

// This gets called on every request
export async function getServerSideProps(context) {

  const { id } = context.query
  const url = `https://api.spoonacular.com/recipes/${id}/information?&apiKey=${process.env.FOOD_API_KEY}`
  console.log("url for food/id page: ", url)
  // Fetch data from external API
  const result = await fetch(`${url}`, {
    method: "GET",
    headers: {
      'Content-Type': 'application/json'
      // 'Content-Type': 'application/x-www-form-urlencoded',
    },
  })
  const data = await result.json()
  console.log("Server side fetch: ", data)

  // Pass data to the page via props
  return { props: { data } }
}

export default foodPage