import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import FoodForm from '../Components/FoodForm'
import { useState } from 'react'
export default function Home() {

  const [foodData, SetFoodData] = useState({})
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex justify-center items-center h-screen'>
        <div className='bg-slate-400 p-5 rounded-lg'>
          <FoodForm passData={SetFoodData}/>


        </div>
        <p>{foodData.result?.results?.length}</p>




      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
